<?php
$prod_data_output = '';
$prod_data_output .= '<h3>Hello ' . get_dealer_name( $entry ) . '</h3>';
$prod_data_output .= '<p>You have received a quote request through <a href="http://hvacinstantquote.com/">HVAC Instant Quote</a>. Please contact this customer immediately to schedule their in home visit to assess and provide installation costs.</p>';
$prod_data_output .= '<table width="99%" border="0" cellpadding="1" cellspacing="0" bgcolor="#EAEAEA">';
$prod_data_output .= '<tr>';
$prod_data_output .= '<td>';
$prod_data_output .= '<table width="100%" border="0" cellpadding="5" cellspacing="0" bgcolor="#FFFFFF">';
$prod_data_output .= '<tbody>';
$prod_data_output .= '<tr>';
$prod_data_output .= '<td colspan="2" style="font-size:14px;font-weight:bold;background-color:#eee;border-bottom:1px solid #dfdfdf;padding:7px 7px">Customer Contact Information</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#EAF2FA">';
$prod_data_output .= '<td colspan="2">';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px"><strong>Quote ID Number</strong></font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#FFFFFF">';
$prod_data_output .= '<td width="20">&nbsp;</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . rgar( $entry, 'id' ) . ' ' . rgar( $entry, '11.6' ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#EAF2FA">';
$prod_data_output .= '<td colspan="2">';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px"><strong>Entry Date</strong></font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#FFFFFF">';
$prod_data_output .= '<td width="20">&nbsp;</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . rgar( $entry, 'date_created' ) . ' ' . rgar( $entry, '11.6' ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#EAF2FA">';
$prod_data_output .= '<td colspan="2">';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px"><strong>Name</strong></font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#FFFFFF">';
$prod_data_output .= '<td width="20">&nbsp;</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . rgar( $entry, '11.3' ) . ' ' . rgar( $entry, '11.6' ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#EAF2FA">';
$prod_data_output .= '<td colspan="2">';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px"><strong>Phone</strong></font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#FFFFFF">';
$prod_data_output .= '<td width="20">&nbsp;</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . rgar( $entry, '48' ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#EAF2FA">';
$prod_data_output .= '<td colspan="2">';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px"><strong>Email</strong></font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#FFFFFF">';
$prod_data_output .= '<td width="20">&nbsp;</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . rgar( $entry, '12' ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '</tbody>';
$prod_data_output .= '</table>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '</table>';
$prod_data_output .= '<table width="99%" border="0" cellpadding="1" cellspacing="0" bgcolor="#EAEAEA">';
$prod_data_output .= '<tr>';
$prod_data_output .= '<td>';
$prod_data_output .= '<table width="100%" border="0" cellpadding="5" cellspacing="0" bgcolor="#FFFFFF">';
$prod_data_output .= '<tbody>';
$prod_data_output .= '<tr>';
$prod_data_output .= '<td colspan="3" style="font-size:14px;font-weight:bold;background-color:#eee;border-bottom:1px solid #dfdfdf;padding:7px 7px">Quote Details:</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#EAF2FA">';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">Selection</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '&nbsp;';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . $prod_string . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#FFFFFF">';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">Outdoor Unit</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . get_post_meta( $product_post_id, 'sqms-product-odu-model', true ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . get_post_meta( $product_post_id, 'sqms-product-odu-price', true ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#EAF2FA">';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">Coil Model</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . get_post_meta( $product_post_id, 'sqms-product-coil-model', true ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . get_post_meta( $product_post_id, 'sqms-product-coil-price', true ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#FFFFFF">';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">Furnace Model</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . get_post_meta( $product_post_id, 'sqms-product-furnace-model', true ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . get_post_meta( $product_post_id, 'sqms-product-furnace-price', true ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#EAF2FA">';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">Total Equipment</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '&nbsp;';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . get_post_meta( $product_post_id, 'sqms-product-system-price', true ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '</tbody>';
$prod_data_output .= '</table>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '</table>';
$prod_data_output .= '<table width="99%" border="0" cellpadding="1" cellspacing="0" bgcolor="#EAEAEA">';
$prod_data_output .= '<tr>';
$prod_data_output .= '<td>';
$prod_data_output .= '<table width="100%" border="0" cellpadding="5" cellspacing="0" bgcolor="#FFFFFF">';
$prod_data_output .= '<tbody>';
$prod_data_output .= '<tr>';
$prod_data_output .= '<td colspan="3" style="font-size:14px;font-weight:bold;background-color:#eee;border-bottom:1px solid #dfdfdf;padding:7px 7px">Performance Data:</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#EAF2FA">';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">Cooling BTU</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '&nbsp;';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . get_post_meta( $product_post_id, 'sqms-product-cooling-btu', true ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#FFFFFF">';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">SEER</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '&nbsp;';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . get_post_meta( $product_post_id, 'sqms-product-seer', true ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#EAF2FA">';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">EER</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '&nbsp;';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . get_post_meta( $product_post_id, 'sqms-product-eer', true ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '</tbody>';
$prod_data_output .= '</table>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '</table>';
$prod_data_output .= '<table width="99%" border="0" cellpadding="1" cellspacing="0" bgcolor="#EAEAEA">';
$prod_data_output .= '<tr>';
$prod_data_output .= '<td>';
$prod_data_output .= '<table width="100%" border="0" cellpadding="5" cellspacing="0" bgcolor="#FFFFFF">';
$prod_data_output .= '<tbody>';
$prod_data_output .= '<tr>';
$prod_data_output .= '<td colspan="3" style="font-size:14px;font-weight:bold;background-color:#eee;border-bottom:1px solid #dfdfdf;padding:7px 7px">Application Data:</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#EAF2FA">';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">Application</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '&nbsp;';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . get_post_meta( $product_post_id, 'sqms-product-application', true ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '<tr bgcolor="#FFFFFF">';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">Voltage</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '&nbsp;';
$prod_data_output .= '</td>';
$prod_data_output .= '<td>';
$prod_data_output .= '<font style="font-family:sans-serif;font-size:12px">' . get_post_meta( $product_post_id, 'sqms-product-odu-voltage', true ) . '</font>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '</tbody>';
$prod_data_output .= '</table>';
$prod_data_output .= '</td>';
$prod_data_output .= '</tr>';
$prod_data_output .= '</table>';
